In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/spamham-emails/spam.csv


In [3]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [4]:
df=pd.read_csv('/kaggle/input/spamham-emails/spam.csv')
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
df['Category'].value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [6]:
df['spam']=df['Category'].apply(lambda x:1 if x=="spam" else 0)

In [7]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [8]:
X=df['Message']
y=df['spam']
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3, random_state=0)

In [9]:
X_train.shape

(3900,)

In [10]:
X_test.shape

(1672,)

In [12]:
X_train[:5]

4380                 How are you. Just checking up on you
3887    Same, I'm at my great aunts anniversary party ...
4755                   Ok lor... Or u wan me go look 4 u?
2707    S now only i took tablets . Reaction morning o...
4747           Orh i tot u say she now still dun believe.
Name: Message, dtype: object

In [13]:
y_train[:5]

4380    0
3887    0
4755    0
2707    0
4747    0
Name: spam, dtype: int64

In [14]:
X_train.values

array(['How are you. Just checking up on you',
       "Same, I'm at my great aunts anniversary party in tarpon springs",
       'Ok lor... Or u wan me go look 4 u?', ...,
       "For ur chance to win a £250 cash every wk TXT: ACTION to 80608. T's&C's www.movietrivia.tv custcare 08712405022, 1x150p/wk",
       'R U &SAM P IN EACHOTHER. IF WE MEET WE CAN GO 2 MY HOUSE',
       'Mm feeling sleepy. today itself i shall get that dear'],
      dtype=object)

In [18]:
from sklearn.feature_extraction.text import CountVectorizer
v= CountVectorizer()
X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<3900x7309 sparse matrix of type '<class 'numpy.int64'>'
	with 52055 stored elements in Compressed Sparse Row format>

In [31]:
X_test_cv = v.transform(X_test.values)

In [19]:
X_train_cv.toarray()[:5]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [20]:
X_train_cv.shape

(3900, 7309)

In [24]:
v.get_feature_names_out()[1000:1100]

array(['arrested', 'arrive', 'arrived', 'arrow', 'arsenal', 'art',
       'artists', 'arts', 'arun', 'as', 'asap', 'asda', 'ashes', 'ashley',
       'ashwini', 'asia', 'asian', 'asjesus', 'ask', 'askd', 'asked',
       'askin', 'asking', 'asks', 'asleep', 'asp', 'aspects', 'ass',
       'assessment', 'asshole', 'assistance', 'associate',
       'asssssholeeee', 'assume', 'assumed', 'asthma', 'astoundingly',
       'astronomer', 'asus', 'asusual', 'at', 'ate', 'athletic',
       'atlanta', 'atlast', 'atleast', 'atm', 'atrocious', 'attach',
       'attached', 'attack', 'attempt', 'atten', 'attend', 'attended',
       'attending', 'attitude', 'attractive', 'attracts', 'attributed',
       'auction', 'audition', 'audrey', 'audrie', 'august', 'auntie',
       'aunties', 'aunts', 'aunty', 'auto', 'autocorrect', 'ava',
       'availa', 'available', 'avalarr', 'avatar', 'ave', 'avenge',
       'avent', 'avenue', 'avin', 'avo', 'avoid', 'avoiding', 'avoids',
       'await', 'awaiting', 'awake',

In [27]:
v.get_feature_names_out()[3309]

'how'

In [26]:
v.vocabulary_

{'how': 3309,
 'are': 973,
 'you': 7275,
 'just': 3655,
 'checking': 1632,
 'up': 6783,
 'on': 4638,
 'same': 5555,
 'at': 1040,
 'my': 4388,
 'great': 3041,
 'aunts': 1067,
 'anniversary': 907,
 'party': 4791,
 'in': 3427,
 'tarpon': 6334,
 'springs': 6051,
 'ok': 4622,
 'lor': 3964,
 'or': 4674,
 'wan': 6961,
 'me': 4148,
 'go': 2972,
 'look': 3953,
 'now': 4555,
 'only': 4648,
 'took': 6587,
 'tablets': 6302,
 'reaction': 5268,
 'morning': 4315,
 'orh': 4689,
 'tot': 6604,
 'say': 5585,
 'she': 5725,
 'still': 6114,
 'dun': 2317,
 'believe': 1213,
 'no': 4509,
 'current': 1968,
 'and': 896,
 'food': 2738,
 'here': 3208,
 'am': 872,
 'alone': 859,
 'also': 864,
 'these': 6456,
 'won': 7155,
 'do': 2210,
 'have': 3152,
 'to': 6550,
 'move': 4332,
 'morphine': 4317,
 'can': 1514,
 'all': 850,
 'decide': 2048,
 'faster': 2591,
 'cos': 1875,
 'sis': 5838,
 'going': 2981,
 'home': 3266,
 'liao': 3853,
 'dear': 2038,
 'good': 2991,
 'oh': 4617,
 'think': 6464,
 'most': 4320,
 'of': 4600,
 

In [25]:
dir(v)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_validate_ngram_range',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',
 'build_preprocessor',
 'bui

In [28]:
X_train_np = X_train_cv.toarray()
X_train_np[:5]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [29]:
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [30]:
np.where(X_train_np[0]!=0)

(array([ 973, 1632, 3309, 3655, 4638, 6783, 7275]),)

In [32]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()

model.fit(X_train_cv, y_train)

MultinomialNB()

In [33]:
from sklearn.metrics import classification_report
y_pred= model.predict(X_test_cv)

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99      1451
           1       0.98      0.91      0.94       221

    accuracy                           0.99      1672
   macro avg       0.98      0.96      0.97      1672
weighted avg       0.99      0.99      0.99      1672



In [34]:
emails=["Hey Mohan , can we get together to watch football game tomorrow?",
       "Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!"]

In [35]:
emails_count=v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [36]:
from sklearn.pipeline import Pipeline

clf= Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb',MultinomialNB())
])

In [37]:
clf.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [38]:
from sklearn.metrics import classification_report
y_pred= clf.predict(X_test)

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99      1451
           1       0.98      0.91      0.94       221

    accuracy                           0.99      1672
   macro avg       0.98      0.96      0.97      1672
weighted avg       0.99      0.99      0.99      1672



In [39]:
clf.predict(emails)

array([0, 1])